// Bestdori emoji names are generated from module 914f and mirrored under public/res/emoji.
// Custom Discord emoji are inserted into the same character-grouped order.
export const COMMENT_EMOJI_NAMES = [
  "KasumiCry",
  "KasumiYay",
  "NotLikeKasumi",
  "Tae",
  "TaeHuh",
  "TaeSpook",
  "RimiBoo",
  "RimiDrool",
  "RimiShook",
  "SaayaMelt",
  "SaayaWhat",
  "SaayaXD",
  "ArisaAngery",
  "ArisaHuh",
  "ArisaJii",
  "RanBlush",
  "Ranguish",
  "RanPat",
  "Mocappa",
  "MocaSmirk",
  "MocaThink",
  "HimariLewd",
  "HimariLul",
  "HimariPout",
  "TomoeDrool",
  "TomoeEmbarassed",
  "TomoeSmug",
  "NotLikeTsugu",
  "Tsugu",
  "Tsugurific",
  "KokoroPeek",
  "KokoroSlain",
  "KokoroJii",
  "KokoroYay",
  "KaoruBrag",
  "KaoruFiget",
  "KaoruShrug",
  "HagumiAngry",
  "HagumiCry",
  "HagumiXD",
  "KanonJii",
  "KanonFuee",
  "KanonHurt",
  "KanonLove",
  "MichelleDab",
  "MisakiSleeper",
  "MisakiWoah",
  "AyaDed",
  "AyaJii",
  "AyaWow",
  "HinaAAA",
  "HinaLul",
  "HinaSmug",
  "HinaYay",
  "ChisatoJii",
  "ChisatoWorry",
  "ChisatoWTF",
  "ChisatoBonk",
  "MayaBomb",
  "MayaShook",
  "MayaThink",
  "Eve",
  "EveBushido",
  "NotLikeEve",
  "YukinaShrug",
  "YukinaYay",
  "Yukinya",
  "SayoAngery",
  "SayoBruh",
  "SayoPensive",
  "LisaMelt",
  "LisaSmug",
  "LisaSparkle",
  "AkoCop",
  "AkoFuee",
  "AkoPanic",
  "RinkoDed",
  "RinkoSparkle",
  "RinkoWhat",
  "MashiroJii",
  "MashiroGlasses",
  "MashiroSweat",
  "ToukoNya",
  "ToukoJii",
  "ToukoCheer",
  "NanamiVibin",
  "NanamiGiggle",
  "NanamiJii",
  "NanamiWink",
  "TsukushiFidget",
  "TsukushiShook",
  "TsukushiShock",
  "RuiPerfect",
  "RuiFuee",
  "RuiThink",
  "LayerBashful",
  "LayerBliss",
  "LayerShock",
  "LayerSit",
  "LockBliss",
  "LockScared",
  "LockSleeper",
  "MaskingGlare",
  "MaskingJii",
  "MaskingPensive",
  "PareoJii",
  "PareoThink",
  "PareoXD",
  "Chu2Peek",
  "Chu2Ping",
  "Chu2Pog",
  "MarinaSlain",
  "KasumiToyama",
  "TaeHanazono",
  "RimiUshigome",
  "SayaYamabuki",
  "ArisaIchigaya",
  "RanMitake",
  "MocaAoba",
  "HimariUehara",
  "TomoeUdagawa",
  "TsugumiHazawa",
  "KokoroTsurumaki",
  "KaoruSeta",
  "HagumiKitazawa",
  "KanonMatsubara",
  "MisakiOkusawa",
  "AyaMaruyama",
  "HinaHikawa",
  "ChisatoShirasagi",
  "MayaYamato",
  "EveWakamiya",
  "YukinaMinato",
  "SayoHikawa",
  "LisaImai",
  "AkoUdagawa",
  "RinkoShirokane",
  "MashiroKurata",
  "ToukoKirigaya",
  "NanamiHiromachi",
  "TsukushiFutaba",
  "RuiYashio",
  "ReiWakana",
  "RokkaAsahi",
  "MasukiSato",
  "ReonaNyubara",
  "ChiyuTamade",
  "PoPiPa",
  "Afterglow",
  "HaroHapi",
  "PasuPare",
  "Roselia",
  "Morfonica",
  "RAS",
  "Power",
  "Cool",
  "Happy",
  "Pure"
] as const;

export const CUSTOM_COMMENT_EMOJIS = [
  { name: "KanonJii", src: "/res/emoji/KanonJii.webp" },
  { name: "KokoroJii", src: "/res/emoji/KokoroJii.webp" },
  { name: "HinaLul", src: "/res/emoji/HinaLul.webp" },
  { name: "NanamiGiggle", src: "/res/emoji/NanamiGiggle.webp" },
  { name: "MarinaSlain", src: "/res/emoji/MarinaSlain.webp" },
  { name: "LayerBashful", src: "/res/emoji/LayerBashful.webp" },
  { name: "ChisatoBonk", src: "/res/emoji/ChisatoBonk.webp" },
] as const;

export type CommentEmojiName = (typeof COMMENT_EMOJI_NAMES)[number];

export const COMMENT_EMOJI_NAME_SET: ReadonlySet<string> = new Set(COMMENT_EMOJI_NAMES);

const CUSTOM_COMMENT_EMOJI_SRC_BY_NAME: ReadonlyMap<string, string> = new Map(
  CUSTOM_COMMENT_EMOJIS.map((emoji) => [emoji.name, emoji.src]),
);

export function getCommentEmojiSrc(name: string): string | null {
  const customSrc = CUSTOM_COMMENT_EMOJI_SRC_BY_NAME.get(name);
  if (customSrc) return customSrc;

  return COMMENT_EMOJI_NAME_SET.has(name) ? `/res/emoji/${name}.png` : null;
}
