import { getApiErrorCode, getApiErrorMessage } from "@/lib/api-contracts";

const LOCALIZED_API_ERROR_CODES = new Set([
  "INVALID_LOGIN_REQUEST",
  "USER_SNAPSHOT_UNAVAILABLE",
  "LOGIN_TASK_ACTIVE",
  "LOGIN_TASK_BUSY",
  "LOGIN_ACCOUNT_BUSY",
  "LOGIN_TASK_NOT_FOUND",
  "LOGIN_TASK_EXPIRED",
  "LOGIN_UPSTREAM_UNAVAILABLE",
  "LOGIN_NOT_COMPLETED",
  "LOGIN_TARGET_MISMATCH",
  "LOGIN_GAME_MAINTENANCE",
  "LOGIN_VERIFICATION_FAILED",
  "LOGIN_UPSTREAM_TIMEOUT",
  "LOGIN_UPSTREAM_CONNECTION_FAILED",
  "LOGIN_OPERATION_TIMEOUT",
  "LOGIN_DATA_INVALID",
  "LOGIN_RESPONSE_TOO_LARGE",
  "GAME_PROFILE_SYNC_FAILED",
  "TRACKER_SERVICE_FAILED",
  "TRACKER_SERVICE_NOT_CONFIGURED",
  "TRACKER_SERVICE_INVALID_RESPONSE",

  "UNAUTHENTICATED",
  "INVALID_AUTHORIZATION_HEADER",
  "AUTHENTICATION_FAILED",
  "EMAIL_VERIFICATION_REQUIRED",
  "INVALID_JSON",
  "INVALID_REQUEST",
  "INVALID_USERNAME",
  "INVALID_PASSWORD",
  "USERNAME_TAKEN",
  "USERNAME_CHECK_FAILED",
  "EMAIL_TAKEN",
  "EMAIL_UNCHANGED",
  "EMAIL_REQUIRED",
  "SIGN_UP_FAILED",
  "PASSWORD_RESET_FAILED",
  "EMAIL_UPDATE_FAILED",
  "TURNSTILE_SERVER_NOT_CONFIGURED",
  "TURNSTILE_REQUIRED",
  "TURNSTILE_VERIFY_FAILED",
  "TURNSTILE_INVALID",
  "PROFILE_READ_FAILED",
  "PROFILE_CREATE_FAILED",
  "ACCOUNT_PROFILE_UPDATE_FAILED",
  "INVALID_AVATAR_CARD_ID",
  "ACCOUNT_AVATAR_CARD_SERVER_REQUIRED",
  "INVALID_AVATAR_CARD_TRAIN_TYPE",
  "AVATAR_CARD_NOT_FOUND",
  "INVALID_COMMENT_CONTENT",
  "EMPTY_COMMENT",
  "COMMENT_TOO_LONG",
  "COMMENT_CREATE_FAILED",
]);

type TranslateApiError = (key: string, values?: Record<string, string | number>) => string;

export function isLocalizedApiErrorCode(code: string): boolean {
  return LOCALIZED_API_ERROR_CODES.has(code);
}

export function getLocalizedApiErrorMessage(
  payload: unknown,
  translateApiError: TranslateApiError,
): string | null {
  const code = getApiErrorCode(payload);
  if (code && isLocalizedApiErrorCode(code)) {
    return translateApiError(`api.${code}`);
  }

  return getApiErrorMessage(payload);
}
