/*
 * Medley search constants and runtime feature flags.
 *
 * The flags in this file only select existing proof or heuristic paths. Correctness still
 * depends on search.ts marking bounded runs separately from exact exhaustive proofs.
 */

export const MEDLEY_TEAM_COUNT = 3;

export const MEDLEY_TEAM_SIZE = 5;

export const MEDLEY_SKILL_COEFFICIENT_EPSILON = 1e-9;

export const MEDLEY_CAPACITY_PARETO_TWO_SLOT_STATE_BUDGET = 300_000;

export const MEDLEY_CAPACITY_PARETO_THREE_SLOT_STATE_BUDGET = 80_000;

export const MEDLEY_CAPACITY_DUAL_OBJECTIVE_STATE_BUDGET = 500_000;

export const MEDLEY_CAPACITY_PARETO_GLOBAL_STATE_BUDGET = 1_200_000;

export const MEDLEY_CAPACITY_CARD_BOUND_DUAL_OBJECTIVE_STATE_BUDGET = 2_000_000;

export const MEDLEY_CAPACITY_CARD_BOUND_DUAL_OBJECTIVE_GLOBAL_STATE_BUDGET = 4_000_000;

export const MEDLEY_ENABLE_CARD_BOUND_DUAL_OBJECTIVE_UPPER = false;

export const MEDLEY_ENABLE_LEADER_FIXED_CARD_SPECIFIC_UPPER = false;

export const MEDLEY_ENABLE_LEADER_GROUP_CARD_SPECIFIC_UPPER = false;

export const MEDLEY_ENABLE_CONTEXT_FIXED_CARD_SPECIFIC_UPPER = true;

export const MEDLEY_ENABLE_CONTEXT_GROUP_CARD_SPECIFIC_UPPER = true;

export const MEDLEY_ENABLE_CONTEXT_BOUND_LAGRANGIAN_UPPER = false;

export const MEDLEY_CONTEXT_GROUP_CARD_SPECIFIC_TOP_COUNT = 8;

export const MEDLEY_CONTEXT_GROUP_CARD_SPECIFIC_TAIL_GROUP_SIZE = 4;

export const MEDLEY_ENABLE_CONTEXT_BOUND_BUCKETED_JOINT_UPPER = false;

export const MEDLEY_ENABLE_CONTEXT_BOUND_MCCORMICK_UPPER = true;

export const MEDLEY_CONTEXT_BOUND_MCCORMICK_MAX_PROCESSED_COMBINATIONS = 48;

export const MEDLEY_CONTEXT_BOUND_MCCORMICK_SCORE_WINDOW = 80_000;

export const MEDLEY_ENABLE_CONTEXT_BOUND_POWER_SPLIT_MCCORMICK_UPPER = false;

export const MEDLEY_ENABLE_CONTEXT_BOUND_SPLIT_SKILL_MCCORMICK_UPPER = true;

export const MEDLEY_CONTEXT_BOUND_SPLIT_SKILL_MCCORMICK_MAX_PROCESSED_COMBINATIONS = 48;

export const MEDLEY_ENABLE_CONTEXT_BOUND_CARD_BOUND_UPPER = true;

export const MEDLEY_CONTEXT_BOUND_CARD_BOUND_MAX_PROCESSED_COMBINATIONS = 48;

export const MEDLEY_ENABLE_TEAM_SHARED_COEFFICIENT_UPPER = true;

export const MEDLEY_TEAM_SHARED_COEFFICIENT_MAX_PROCESSED_COMBINATIONS = 2;

export const MEDLEY_TEAM_SHARED_COEFFICIENT_INTERVAL_COUNT = 2;

export const MEDLEY_TEAM_SHARED_COEFFICIENT_STATE_BUDGET = 2_500_000;

export const MEDLEY_TEAM_SHARED_COEFFICIENT_GLOBAL_STATE_BUDGET = 5_500_000;

export const MEDLEY_DEFAULT_OPPORTUNITY_ANCHOR_LIMIT = 16;

export const MEDLEY_MAX_OPPORTUNITY_ANCHOR_LIMIT = 48;

export const MEDLEY_CONTEXT_BOUND_POWER_SPLIT_MCCORMICK_MAX_PROCESSED_COMBINATIONS = 4;

export const MEDLEY_CONTEXT_BOUND_POWER_SPLIT_MCCORMICK_BUCKET_COUNT = 4;

export const MEDLEY_CONTEXT_BOUND_POWER_SPLIT_MCCORMICK_STATE_BUDGET = 220_000;

export const MEDLEY_CONTEXT_BOUND_POWER_SPLIT_MCCORMICK_GLOBAL_STATE_BUDGET = 1_200_000;

export const MEDLEY_CONTEXT_BOUND_BUCKETED_JOINT_TARGET_BUCKET_COUNTS = [64, 32, 16, 8] as const;

export const MEDLEY_CONTEXT_BOUND_BUCKETED_JOINT_MIN_BUCKET_SIZE = 500;

export const MEDLEY_CONTEXT_BOUND_BUCKETED_JOINT_MAX_PROCESSED_COMBINATIONS = 8;

export const MEDLEY_CONTEXT_BOUND_BUCKETED_JOINT_SCORE_WINDOW = 35_000;

export const MEDLEY_CONTEXT_BOUND_BUCKETED_JOINT_STATE_BUDGET = 1_500_000;

export const MEDLEY_CONTEXT_BOUND_BUCKETED_JOINT_GLOBAL_STATE_BUDGET = 6_000_000;

export const MEDLEY_LEADER_GROUP_CARD_SPECIFIC_TOP_COUNT = 6;

export const MEDLEY_LEADER_GROUP_CARD_SPECIFIC_TAIL_GROUP_SIZE = 4;

export const MEDLEY_ENABLE_CARD_SPECIFIC_LAGRANGIAN_UPPER = false;

export const MEDLEY_CARD_BOUND_LAGRANGIAN_WEIGHTS = [
  0.05,
  0.1,
  0.15,
  0.2,
  0.25,
  0.3,
  0.35,
  0.4,
  0.45,
  0.5,
  0.55,
  0.6,
  0.65,
  0.7,
  0.75,
  0.8,
  0.85,
  0.9,
  0.925,
  0.95,
  0.975,
  0.99,
] as const;

export const MEDLEY_CONTEXT_BOUND_LAGRANGIAN_WEIGHTS = [0, 0.85, 0.9, 0.95, 0.975, 0.99, 1] as const;

export const MEDLEY_CONTEXT_BOUND_LAGRANGIAN_MAX_GROUP_COMBINATIONS = 1_000;

export const MEDLEY_CARD_BOUND_BUCKETED_JOINT_TARGET_BUCKET_COUNTS = [1024, 512, 256, 128, 64] as const;

export const MEDLEY_CARD_BOUND_BUCKETED_JOINT_MIN_BUCKET_SIZE = 500;

export const MEDLEY_CARD_BOUND_BUCKETED_JOINT_STATE_BUDGET = 1_200_000;

export const MEDLEY_CARD_BOUND_BUCKETED_JOINT_GLOBAL_STATE_BUDGET = 3_000_000;

export const MEDLEY_CARD_MIN_COEFFICIENT_TARGET_BUCKET_COUNTS = [256, 128, 64, 32, 16] as const;

export const MEDLEY_ENABLE_CARD_MIN_COEFFICIENT_UPPER = false;

export const MEDLEY_CARD_MIN_COEFFICIENT_STATE_BUDGET = 1_200_000;

export const MEDLEY_CARD_MIN_COEFFICIENT_GLOBAL_STATE_BUDGET = 3_000_000;

export const MEDLEY_CARD_MIN_COEFFICIENT_DOMINANCE_PRUNE_THRESHOLD = 96;

export const MEDLEY_CAPACITY_BUCKETED_STATE_BUDGET = 2_000_000;

export const MEDLEY_CAPACITY_BUCKETED_GLOBAL_STATE_BUDGET = 6_000_000;

export const MEDLEY_CAPACITY_BUCKETED_TARGET_BUCKET_COUNT = 64;

export const MEDLEY_CAPACITY_BUCKETED_MIN_BUCKET_SIZE = 1_000;

export const MEDLEY_CAPACITY_BUCKETED_BUCKET_SIZE_STEP = 250;

export const MEDLEY_CAPACITY_PARETO_TWO_SLOT_CARD_RECORD_BUDGET = 700;

export const MEDLEY_CAPACITY_PARETO_THREE_SLOT_CARD_RECORD_BUDGET = 450;

export const MEDLEY_ENABLE_BUCKETED_CAPACITY_UPPER = false;

export const MEDLEY_EXACT_CANDIDATE_JOIN_DEFAULT_CANDIDATE_SOFT_LIMIT = 20_000;

export const MEDLEY_EXACT_CANDIDATE_JOIN_DEFAULT_NODE_SOFT_LIMIT = 900_000;

export const MEDLEY_CONFLICT_EXACT_BNB_DEFAULT_NODE_LIMIT = 2_048;

export const MEDLEY_CONFLICT_SLOT_SOLVE_DEFAULT_NODE_LIMIT = 200_000;

export const MEDLEY_DEFAULT_ANCHOR_CANDIDATE_LIMIT = 32;

export const MEDLEY_BAND_ID_BY_AREA_ITEM_KEY: Record<string, number | null> = {
  PoppinParty: 1,
  Afterglow: 2,
  HelloHappyWorld: 3,
  PastelPalettes: 4,
  Roselia: 5,
  Morfonica: 21,
  RaiseASuilen: 18,
  MyGO: 45,
  Everyone: null,
};

export const MEDLEY_PARAMETER_KEYS = ["performance", "technique", "visual"] as const;
