// Reviewed exact aliases; keep punctuation and do not infer additional nicknames.

export { BANDORI_SEARCH_BAND_ALIASES as BANDORI_CARD_SEARCH_BAND_ALIASES } from "@/lib/bandori/search";

export const BANDORI_CARD_SEARCH_CHARACTER_ALIASES: Readonly<Record<number, readonly string[]>> = {
  1: ["香澄","kasumi","戸山","toyama","戶山","户山","香澄戸山","戸山香澄","香澄 戸山","戸山 香澄","kasumitoyama","toyamakasumi","kasumi toyama","toyama kasumi","香澄戶山","戶山香澄","香澄 戶山","戶山 香澄","香澄户山","户山香澄","香澄 户山","户山 香澄","ksm"],
  2: ["たえ","tae","多惠","花園","hanazono","花园","たえ花園","花園たえ","たえ 花園","花園 たえ","taehanazono","hanazonotae","tae hanazono","hanazono tae","多惠花園","花園多惠","多惠 花園","花園 多惠","多惠花园","花园多惠","多惠 花园","花园 多惠","otae","おたえ"],
  3: ["りみ","rimi","里美","牛込","ushigome","りみ牛込","牛込りみ","りみ 牛込","牛込 りみ","rimiushigome","ushigomerimi","rimi ushigome","ushigome rimi","里美牛込","牛込里美","里美 牛込","牛込 里美"],
  4: ["沙綾","saya","沙绫","saaya","山吹","yamabuki","沙綾山吹","山吹沙綾","沙綾 山吹","山吹 沙綾","sayayamabuki","yamabukisaya","saya yamabuki","yamabuki saya","沙绫山吹","山吹沙绫","沙绫 山吹","山吹 沙绫","saayayamabuki","yamabukisaaya","saaya yamabuki","yamabuki saaya"],
  5: ["有咲","arisa","市ヶ谷","ichigaya","市谷","有咲市ヶ谷","市ヶ谷有咲","有咲 市ヶ谷","市ヶ谷 有咲","arisaichigaya","ichigayaarisa","arisa ichigaya","ichigaya arisa","有咲市谷","市谷有咲","有咲 市谷","市谷 有咲","ars"],
  6: ["蘭","ran","兰","美竹","mitake","蘭美竹","美竹蘭","蘭 美竹","美竹 蘭","ranmitake","mitakeran","ran mitake","mitake ran","兰美竹","美竹兰","兰 美竹","美竹 兰"],
  7: ["モカ","moca","摩卡","青葉","aoba","青叶","モカ青葉","青葉モカ","モカ 青葉","青葉 モカ","mocaaoba","aobamoca","moca aoba","aoba moca","摩卡青葉","青葉摩卡","摩卡 青葉","青葉 摩卡","摩卡青叶","青叶摩卡","摩卡 青叶","青叶 摩卡"],
  8: ["ひまり","himari","緋瑪麗","绯玛丽","上原","uehara","ひまり上原","上原ひまり","ひまり 上原","上原 ひまり","himariuehara","ueharahimari","himari uehara","uehara himari","緋瑪麗上原","上原緋瑪麗","緋瑪麗 上原","上原 緋瑪麗","绯玛丽上原","上原绯玛丽","绯玛丽 上原","上原 绯玛丽","hmr"],
  9: ["巴","tomoe","宇田川","udagawa","巴宇田川","宇田川巴","巴 宇田川","宇田川 巴","tomoeudagawa","udagawatomoe","tomoe udagawa","udagawa tomoe","tme"],
  10: ["つぐみ","tsugumi","鶇","鸫","羽沢","hazawa","羽澤","羽泽","つぐみ羽沢","羽沢つぐみ","つぐみ 羽沢","羽沢 つぐみ","tsugumihazawa","hazawatsugumi","tsugumi hazawa","hazawa tsugumi","鶇羽澤","羽澤鶇","鶇 羽澤","羽澤 鶇","鸫羽泽","羽泽鸫","鸫 羽泽","羽泽 鸫","tsugu","つぐ","tgm"],
  11: ["こころ","kokoro","心","弦巻","tsurumaki","弦卷","こころ弦巻","弦巻こころ","こころ 弦巻","弦巻 こころ","kokorotsurumaki","tsurumakikokoro","kokoro tsurumaki","tsurumaki kokoro","心弦卷","弦卷心","心 弦卷","弦卷 心","kkr"],
  12: ["薫","kaoru","薰","瀬田","seta","瀨田","濑田","薫瀬田","瀬田薫","薫 瀬田","瀬田 薫","kaoruseta","setakaoru","kaoru seta","seta kaoru","薰瀨田","瀨田薰","薰 瀨田","瀨田 薰","薰濑田","濑田薰","薰 濑田","濑田 薰","kor"],
  13: ["はぐみ","hagumi","育美","北沢","kitazawa","北澤","北泽","はぐみ北沢","北沢はぐみ","はぐみ 北沢","北沢 はぐみ","hagumikitazawa","kitazawahagumi","hagumi kitazawa","kitazawa hagumi","育美北澤","北澤育美","育美 北澤","北澤 育美","育美北泽","北泽育美","育美 北泽","北泽 育美","hgm"],
  14: ["花音","kanon","松原","matsubara","花音松原","松原花音","花音 松原","松原 花音","kanonmatsubara","matsubarakanon","kanon matsubara","matsubara kanon"],
  15: ["ミッシェル","misaki","米歇爾","米歇尔","美咲","okusawa","奥沢","奥泽","奧澤","misakiokusawa","okusawamisaki","misaki okusawa","okusawa misaki","美咲奥沢","奥沢美咲","美咲 奥沢","奥沢 美咲","美咲奥泽","奥泽美咲","美咲 奥泽","奥泽 美咲","美咲奧澤","奧澤美咲","美咲 奧澤","奧澤 美咲","msk","michelle"],
  16: ["彩","aya","丸山","maruyama","彩丸山","丸山彩","彩 丸山","丸山 彩","ayamaruyama","maruyamaaya","aya maruyama","maruyama aya"],
  17: ["日菜","hina","氷川","hikawa","冰川","日菜氷川","氷川日菜","日菜 氷川","氷川 日菜","hinahikawa","hikawahina","hina hikawa","hikawa hina","日菜冰川","冰川日菜","日菜 冰川","冰川 日菜"],
  18: ["千聖","chisato","千圣","白鷺","shirasagi","白鹭","千聖白鷺","白鷺千聖","千聖 白鷺","白鷺 千聖","chisatoshirasagi","shirasagichisato","chisato shirasagi","shirasagi chisato","千圣白鹭","白鹭千圣","千圣 白鹭","白鹭 千圣","cst"],
  19: ["麻弥","maya","麻彌","大和","yamato","麻弥大和","大和麻弥","麻弥 大和","大和 麻弥","mayayamato","yamatomaya","maya yamato","yamato maya","麻彌大和","大和麻彌","麻彌 大和","大和 麻彌"],
  20: ["イヴ","eve","伊芙","若宮","wakamiya","若宫","イヴ若宮","若宮イヴ","イヴ 若宮","若宮 イヴ","evewakamiya","wakamiyaeve","eve wakamiya","wakamiya eve","伊芙若宮","若宮伊芙","伊芙 若宮","若宮 伊芙","伊芙若宫","若宫伊芙","伊芙 若宫","若宫 伊芙"],
  21: ["友希那","yukina","湊","minato","凑","友希那湊","湊友希那","友希那 湊","湊 友希那","yukinaminato","minatoyukina","yukina minato","minato yukina","友希那凑","凑友希那","友希那 凑","凑 友希那","ykn"],
  22: ["紗夜","sayo","纱夜","氷川","hikawa","冰川","紗夜氷川","氷川紗夜","紗夜 氷川","氷川 紗夜","sayohikawa","hikawasayo","sayo hikawa","hikawa sayo","紗夜冰川","冰川紗夜","紗夜 冰川","冰川 紗夜","纱夜冰川","冰川纱夜","纱夜 冰川","冰川 纱夜"],
  23: ["リサ","lisa","莉莎","今井","imai","リサ今井","今井リサ","リサ 今井","今井 リサ","lisaimai","imailisa","lisa imai","imai lisa","莉莎今井","今井莉莎","莉莎 今井","今井 莉莎"],
  24: ["あこ","ako","亞子","亚子","宇田川","udagawa","あこ宇田川","宇田川あこ","あこ 宇田川","宇田川 あこ","akoudagawa","udagawaako","ako udagawa","udagawa ako","亞子宇田川","宇田川亞子","亞子 宇田川","宇田川 亞子","亚子宇田川","宇田川亚子","亚子 宇田川","宇田川 亚子"],
  25: ["燐子","rinko","白金","shirokane","燐子白金","白金燐子","燐子 白金","白金 燐子","rinkoshirokane","shirokanerinko","rinko shirokane","shirokane rinko","rinrin"],
  26: ["ましろ","mashiro","真白","倉田","kurata","仓田","ましろ倉田","倉田ましろ","ましろ 倉田","倉田 ましろ","mashirokurata","kuratamashiro","mashiro kurata","kurata mashiro","真白倉田","倉田真白","真白 倉田","倉田 真白","真白仓田","仓田真白","真白 仓田","仓田 真白","shiro","シロ","msr"],
  27: ["透子","toko","touko","桐ヶ谷","kirigaya","桐谷","透子桐ヶ谷","桐ヶ谷透子","透子 桐ヶ谷","桐ヶ谷 透子","tokokirigaya","kirigayatoko","toko kirigaya","kirigaya toko","透子桐谷","桐谷透子","透子 桐谷","桐谷 透子","toukokirigaya","kirigayatouko","touko kirigaya","kirigaya touko"],
  28: ["七深","nanami","広町","hiromachi","廣町","广町","七深広町","広町七深","七深 広町","広町 七深","nanamihiromachi","hiromachinanami","nanami hiromachi","hiromachi nanami","七深廣町","廣町七深","七深 廣町","廣町 七深","七深广町","广町七深","七深 广町","广町 七深","nnm"],
  29: ["つくし","tsukushi","筑紫","二葉","futaba","二叶","つくし二葉","二葉つくし","つくし 二葉","二葉 つくし","tsukushifutaba","futabatsukushi","tsukushi futaba","futaba tsukushi","筑紫二葉","二葉筑紫","筑紫 二葉","二葉 筑紫","筑紫二叶","二叶筑紫","筑紫 二叶","二叶 筑紫","tks"],
  30: ["瑠唯","rui","八潮","yashio","瑠唯八潮","八潮瑠唯","瑠唯 八潮","八潮 瑠唯","ruiyashio","yashiorui","rui yashio","yashio rui"],
  31: ["レイ","rei","瑞依","和奏","wakana","レイヤ","layer","レイ和奏","和奏レイ","レイ 和奏","和奏 レイ","reiwakana","wakanarei","rei wakana","wakana rei","瑞依和奏","和奏瑞依","瑞依 和奏","和奏 瑞依"],
  32: ["六花","rokka","朝日","asahi","ロック","lock","六花朝日","朝日六花","六花 朝日","朝日 六花","rokkaasahi","asahirokka","rokka asahi","asahi rokka"],
  33: ["ますき","masuki","益木","佐藤","sato","マスキング","masking","ますき佐藤","佐藤ますき","ますき 佐藤","佐藤 ますき","masukisato","satomasuki","masuki sato","sato masuki","益木佐藤","佐藤益木","益木 佐藤","佐藤 益木"],
  34: ["令王那","reona","鳰原","nyubara","パレオ","pareo","令王那鳰原","鳰原令王那","令王那 鳰原","鳰原 令王那","reonanyubara","nyubarareona","reona nyubara","nyubara reona"],
  35: ["ちゆ","chiyu","知由","珠手","tamade","チュチュ","chu2","ちゆ珠手","珠手ちゆ","ちゆ 珠手","珠手 ちゆ","chiyutamade","tamadechiyu","chiyu tamade","tamade chiyu","知由珠手","珠手知由","知由 珠手","珠手 知由","chuchu","chu"],
  36: ["燈","tomori","灯","高松","takamatsu","燈高松","高松燈","燈 高松","高松 燈","tomoritakamatsu","takamatsutomori","tomori takamatsu","takamatsu tomori","灯高松","高松灯","灯 高松","高松 灯","tomorin","ともりん","tmr"],
  37: ["愛音","anon","爱音","千早","chihaya","愛音千早","千早愛音","愛音 千早","千早 愛音","anonchihaya","chihayaanon","anon chihaya","chihaya anon","爱音千早","千早爱音","爱音 千早","千早 爱音"],
  38: ["楽奈","rana","樂奈","乐奈","raana","要","kaname","楽奈要","要楽奈","楽奈 要","要 楽奈","ranakaname","kanamerana","rana kaname","kaname rana","樂奈要","要樂奈","樂奈 要","要 樂奈","乐奈要","要乐奈","乐奈 要","要 乐奈","raanakaname","kanameraana","raana kaname","kaname raana"],
  39: ["そよ","soyo","爽世","素世","長崎","nagasaki","长崎","そよ長崎","長崎そよ","そよ 長崎","長崎 そよ","soyonagasaki","nagasakisoyo","soyo nagasaki","nagasaki soyo","爽世長崎","長崎爽世","爽世 長崎","長崎 爽世","爽世长崎","长崎爽世","爽世 长崎","长崎 爽世","素世长崎","长崎素世","素世 长崎","长崎 素世","素世長崎","長崎素世","素世 長崎","長崎 素世","soyorin","そよりん"],
  40: ["立希","taki","椎名","shina","shiina","立希椎名","椎名立希","立希 椎名","椎名 立希","takishina","shinataki","taki shina","shina taki","takishiina","shiinataki","taki shiina","shiina taki","rikki"],
};
